version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: antd
    versions:
    - ">= 4.a, < 5"
  - dependency-name: core-js
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: core-js
    versions:
    - ">= 3.a, < 4"
  - dependency-name: rc-tools
    versions:
    - "< 10, >= 9.a"
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react
    versions:
    - 17.0.1
